[package]
name = "blackmagic-camera-control"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
btleplug = "0.8.1"
bytes = "1.0.1"
enum-primitive-derive = "0.2.1"
enum_primitive = "0.1.1"
fixed = "1.9.0"
futures = "0.3.16"
num = "0.4.0"
num-derive = "0.3.3"
num-traits = "0.2.14"
pretty_env_logger = "0.4.0"
thiserror = "1.0.26"
tokio = { version = "1.10.0", features = ["full"] }
uuid = { version = "0.8.2", features = ["serde", "v5"] }
